### ISSUE TITLE
Readme: The Short Description section is too long and was truncated. A maximum of 150 characters is supported.

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-with-mollie-for-woocommerce#1]
We have the following notice on https://wordpress.org/plugins/pronamic-pay-with-mollie-for-woocommerce/:

> During the last import of your plugin the following warnings were encountered. This message is visible only to the plugin authors & committers.
> 
> Readme: The Short Description section is too long and was truncated. A maximum of 150 characters is supported.

<img width="976" alt="Scherm­afbeelding 2024-03-27 om 16 50 16" src="https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-woocommerce/assets/869674/5516010a-63e3-46e4-bb9f-560c77158708">

---

https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-woocommerce/blob/59c098a2a390c14b6884578e44729b0219b6f61d/readme.txt#L11

This was expanded by @LeoOosterloo in https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-woocommerce/commit/36709d8b998aa1c0de9d2142119637bfb90192c7, I will revert it back for now.

**Comment by remcotolsma** [comment]
Shortened in b0d7a5fdaba7a5d435432be8fa54ac4be04e4d1a, @LeoOosterloo a more detailed description can be added under `== Description ==`:

https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-woocommerce/blob/afd04eeb0eb89b8b5ce900505b2d987bcf51db82/readme.txt#L10-L16

**Comment by LeoOosterloo** [comment]
You use the description we previously use for the short description and move the longer description below the Description title:

https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-woocommerce/blob/59c098a2a390c14b6884578e44729b0219b6f61d/readme.txt#L13
